version: '3.8'

services:
  giropops-senhas:
    container_name: giropops-senhas
    image: jvlr9510/chainguard-giropops-senhas:latest
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis:7.2

networks:
  redis-net:
