apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: giropops-senhas-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.giropopsSenhas.name }}
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: ContainerResource
      containerResource:
        container: giropops-senhas
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
      - type: Percent
        value: 100
        periodSeconds: 10
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 100
        periodSeconds: 10
