apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor 
metadata: 
  name: giropops-servicemonitor 
  labels: 
    app: {{ .Values.giropopsSenhas.labels.app }}
    owner: {{ .Values.giropopsSenhas.labels.owner }}
    type: {{ .Values.giropopsSenhas.labels.type }}
spec: 
  selector: 
    matchLabels: 
      app: {{ .Values.giropopsSenhas.labels.app }}
  endpoints: 
    - interval: 10s 
      path: /metrics 
      port: tcp-app 
