apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-giropops-senhas-ingress-host
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  ingressClassName: nginx
  rules:
  - host: giropops-helm.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.giropopsSenhas.service.name }}
            port:
              number: {{ .Values.giropopsSenhas.service.port }}
